### Products
GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "quantity": 10,
    "price": 100
}

### 
@product_id = 96117c13-a67f-46d7-bc7c-713eb983bce2

### Customers
GET http://localhost:3000/customers

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "email": "customer@customer.com",
    "address": "Customer Address",
    "phone": "123456789"
}

###
@customer_id = d5b7ef96-c14a-455a-9eb1-6de2c7cff4e1

### Orders
GET http://localhost:3000/orders

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "items": [
        {
            "product_id": "{{product_id}}",
            "quantity": 1
        }
    ]
}