### Products
GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "quantity": 10,
    "price": 100
}

### 
@product_id = 49c57811-fbee-45e6-8cdb-e3aca0f51218

### Customers
GET http://localhost:3000/customers

###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1",
    "email": "customer@customer.com",
    "address": "Customer Address",
    "phone": "123456789"
}

###
@customer_id = 5d15c2b6-c7cf-4282-a586-66ef53491c93

### Orders
GET http://localhost:3000/orders

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "customer_id": "{{customer_id}}",
    "items": [
        {
            "product_id": "{{product_id}}",
            "quantity": 1
        }
    ]
}